# Projet 3

In [1]:
# on va importe tout les bibliotheques qu'on aura besoin d'utiliser 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Question 1

In [2]:
#on afficher d'abord le tableaux de population en trieant les pays 
population = pd.read_csv('fr_population.csv')
population.sort_values(by=['Zone'])

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,225,Émirats arabes unis,511,Population totale,2501,Population,2013,2013,1000 personnes,9346,NaN,Donnée officielle
51,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,58,Équateur,511,Population totale,2501,Population,2013,2013,1000 personnes,15738,NaN,Donnée officielle
55,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,231,États-Unis d'Amérique,511,Population totale,2501,Population,2013,2013,1000 personnes,320051,NaN,Donnée officielle
56,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,238,Éthiopie,511,Population totale,2501,Population,2013,2013,1000 personnes,94101,NaN,Donnée officielle
74,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,25,Îles Salomon,511,Population totale,2501,Population,2013,2013,1000 personnes,561,NaN,Donnée officielle

2 Afghanistan
202 Afrique du Sud
3 Albanie
4 Algérie
79 Allemagne
7 Angola
8 Antigua-et-Barbuda
194 Arabie saoudite
9 Argentine
1 Arménie
10 Australie
11 Autriche
52 Azerbaïdjan
12 Bahamas
16 Bangladesh
14 Barbade
57 Bélarus
255 Belgique
23 Belize
53 Bénin
17 Bermudes
19 Bolivie (État plurinational de)
80 Bosnie-Herzégovine
20 Botswana
21 Brésil
26 Brunéi Darussalam
27 Bulgarie
233 Burkina Faso
35 Cabo Verde
115 Cambodge
32 Cameroun
33 Canada
40 Chili
351 Chine
96 Chine - RAS de Hong-Kong
128 Chine - RAS de Macao
41 Chine, continentale
214 Chine, Taiwan Province de
50 Chypre
44 Colombie
46 Congo
48 Costa Rica
107 Côte d'Ivoire
98 Croatie
49 Cuba
54 Danemark
72 Djibouti
55 Dominique
59 Égypte
60 El Salvador
225 Émirats arabes unis
58 Équateur
203 Espagne
63 Estonie
209 Eswatini
231 États-Unis d'Amérique
238 Éthiopie
185 Fédération de Russie
66 Fidji
67 Finlande
68 France
74 Gabon
75 Gambie
73 Géorgie
81 Ghana
84 Grèce
86 Grenade
89 Guatemala
90 Guinée
175 Guinée-Bissau
91 Guyana
93 Haïti
95 Honduras
97 Hongrie
25 Îles Salomon
100 Inde
101 Indonésie
102 Iran (République islamique d')
103 Iraq
104 Irlande
99 Islande
105 Israël
106 Italie
109 Jamaïque
110 Japon
112 Jordanie
108 Kazakhstan
114 Kenya
113 Kirghizistan
83 Kiribati
118 Koweït
122 Lesotho
119 Lettonie
121 Liban
123 Libéria
126 Lituanie
256 Luxembourg
154 Macédoine du Nord
129 Madagascar
131 Malaisie
130 Malawi
132 Maldives
133 Mali
134 Malte
143 Maroc
137 Maurice
136 Mauritanie
138 Mexique
141 Mongolie
273 Monténégro
144 Mozambique
28 Myanmar
147 Namibie
149 Népal
157 Nicaragua
158 Niger
159 Nigéria
162 Norvège
153 Nouvelle-Calédonie
156 Nouvelle-Zélande
221 Oman
226 Ouganda
235 Ouzbékistan
165 Pakistan
166 Panama
169 Paraguay
150 Pays-Bas
170 Pérou
171 Philippines
173 Pologne
70 Polynésie française
174 Portugal
37 République centrafricaine
117 République de Corée
146 République de Moldova
120 République démocratique populaire lao
56 République dominicaine
116 République populaire démocratique de Corée
215 République-Unie de Tanzanie
183 Roumanie
229 Royaume-Uni
184 Rwanda
189 Sainte-Lucie
188 Saint-Kitts-et-Nevis
191 Saint-Vincent-et-les Grenadines
244 Samoa
193 Sao Tomé-et-Principe
195 Sénégal
272 Serbie
197 Sierra Leone
199 Slovaquie
198 Slovénie
276 Soudan
38 Sri Lanka
210 Suède
211 Suisse
207 Suriname
208 Tadjikistan
39 Tchad
167 Tchéquie (la)
216 Thaïlande
176 Timor-Leste
217 Togo
220 Trinité-et-Tobago
222 Tunisie
213 Turkménistan
223 Turquie
230 Ukraine
234 Uruguay
155 Vanuatu
236 Venezuela (République bolivarienne du)
237 Viet Nam
249 Yémen
251 Zambie
181 Zimbabwe

on remarque qu'il ya la Chine et les provences de Chine ,c'est à dire qu'il ya les chiffres en double pour la chine

In [4]:
# Suppression de Redondance (les provinces de chine)
Population_finale=population[~population['Zone'].isin(['Chine - RAS de Hong-Kong', 'Chine - RAS de Macao','Chine, continentale','Chine, Taiwan Province de'])]
Population_finale

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,236,Venezuela (République bolivarienne du),511,Population totale,2501,Population,2013,2013,1000 personnes,30405,NaN,Donnée officielle
171,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,237,Viet Nam,511,Population totale,2501,Population,2013,2013,1000 personnes,91680,NaN,Donnée officielle
172,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,249,Yémen,511,Population totale,2501,Population,2013,2013,1000 personnes,24407,NaN,Donnée officielle
173,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,251,Zambie,511,Population totale,2501,Population,2013,2013,1000 personnes,14539,NaN,Donnée officielle
174,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,511,Population totale,2501,Population,2013,2013,1000 personnes,14150,NaN,Donnée officielle

In [5]:
#on fait la somme de valuers en 2013
Population_Mondiale= Population_finale['Valeur'].sum()*1000
Population_Mondiale

6997326000

# question 2

In [6]:
vegetaux= pd.read_csv('fr_vegetaux.csv')
vegetaux

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104867,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104868,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.00,Fc,Donnée calculée
104869,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée
104870,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,2013,g/personne/jour,0.03,Fc,Donnée calculée

In [7]:
vegetaux.sort_values(by=['Zone'])
vegetaux['Origine']='vegetal'
vegetaux

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Origine
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.00,S,Données standardisées,vegetal
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.00,S,Données standardisées,vegetal
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.00,S,Données standardisées,vegetal
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.00,S,Données standardisées,vegetal
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.00,S,Données standardisées,vegetal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,vegetal
104867,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,vegetal
104868,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.00,Fc,Donnée calculée,vegetal
104869,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée,vegetal
104870,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,2013,g/personne/jour,0.03,Fc,Donnée calculée,vegetal

In [8]:
animaux= pd.read_csv('fr_animaux.csv')
animaux

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,0.00,S,Données standardisées
37162,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,0.00,Fc,Donnée calculée
37163,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,0.00,Fc,Donnée calculée
37164,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
37165,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée

In [9]:
animaux.sort_values(by=['Zone'])
animaux['Origine']='animal'

In [10]:
#on va fusionner vetegataux et animaux avec la fonction append pour former un dataset Bilan alimentaire 
BilanAlimentaire=vegetaux.append(animaux, ignore_index=True)
BilanAlimentaire

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Origine
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.0,S,Données standardisées,vegetal
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.0,S,Données standardisées,vegetal
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.0,S,Données standardisées,vegetal
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.0,S,Données standardisées,vegetal
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.0,S,Données standardisées,vegetal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142032,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,0.0,S,Données standardisées,animal
142033,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,0.0,Fc,Donnée calculée,animal
142034,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,0.0,Fc,Donnée calculée,animal
142035,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.0,Fc,Donnée calculée,animal
142036,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.0,Fc,Donnée calculée,animal

In [11]:
BilanAlimentaire_pivot=BilanAlimentaire.pivot_table(index=['Code zone','Zone','Code Produit','Produit','Année','Origine'],columns='Élément',values='Valeur',aggfunc=sum).reset_index()
BilanAlimentaire_pivot

Élément,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,30.52,554.0,1.0,361.0,389.0,32.0,312.0,30.0,10.0,-118.0
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,0.00,198.0,0.0,9.0,0.0,15.0,189.0,14.0,7.0,0.0
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,0.01,102.0,NaN,82.0,0.0,7.0,21.0,0.0,NaN,NaN
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,0.02,1.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,0.0
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,0.09,6.0,NaN,1.0,1.0,0.0,5.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,0.00,127.0,13.0,91.0,0.0,NaN,50.0,NaN,NaN,0.0
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,0.00,0.0,1.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,14.47,135024.0,565.0,2714.0,109725.0,6406.0,136873.0,4679.0,12.0,-3998.0
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,3.12,50117.0,233.0,9780.0,47009.0,1433.0,40570.0,NaN,0.0,0.0
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Les calcules sont fait par la formule suivante 

## production+importation-exportation+variation de stocks= disponibilite intérieur = semence+ Disponibilité alimentaire +aliments pour animaux+perte + autres utilisations+traitements

In [12]:
# Réponse 2 
#verification de la formule en choisant le blé en France 
#disponibilite intérieur en France on utilisera le bilanalimentaire

Ble_France=BilanAlimentaire_pivot[(BilanAlimentaire_pivot['Zone'] == 'France') & (BilanAlimentaire_pivot['Produit']=='Blé')]

Ble_France

Élément,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
4144,68,France,2511,Blé,2013,vegetal,7822.0,2824.0,811.0,108.43,...,25.99,20298.0,21502.0,2055.0,6971.0,358.0,38614.0,748.0,1575.0,1131.0

In [13]:
DispoInterieur_Gauche=38614.0 + 2055.0 - 21502.0 + 1131.0
DispoInterieur_Gauche # 20298 = Disponibilité intérieure

DispoInterieur_Droite=748.0+ 6971.0+ 7822.0 + 358.0 + 2824.0+ 1575.0
DispoInterieur_Droite #  20298 = Disponibilité intérieure

20298.0

# question 3

In [14]:
BilanAlimentaire_pivot.rename(columns={'Code zone_x': 'Code zone', 'Code Produit_x': 'Code Produit', 'Produit_x': 'Produit', 'Année_x': 'Année', 'Unité_x': 'Unité','Élément_x': 'Élément', 'Valeur' : 'Population'}, inplace=True)
BilanAlimentaire_pivot

Élément,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,30.52,554.0,1.0,361.0,389.0,32.0,312.0,30.0,10.0,-118.0
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,0.00,198.0,0.0,9.0,0.0,15.0,189.0,14.0,7.0,0.0
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,0.01,102.0,NaN,82.0,0.0,7.0,21.0,0.0,NaN,NaN
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,0.02,1.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,0.0
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,0.09,6.0,NaN,1.0,1.0,0.0,5.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,0.00,127.0,13.0,91.0,0.0,NaN,50.0,NaN,NaN,0.0
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,0.00,0.0,1.0,1.0,0.0,NaN,0.0,NaN,NaN,0.0
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,14.47,135024.0,565.0,2714.0,109725.0,6406.0,136873.0,4679.0,12.0,-3998.0
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,3.12,50117.0,233.0,9780.0,47009.0,1433.0,40570.0,NaN,0.0,0.0
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#on va fusionner la population et bilanalimentaire en  pivot 
Bilan=pd.merge(BilanAlimentaire_pivot,population,on='Zone') 
Bilan

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code Élément,Élément,Code Produit_y,Produit_y,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."

In [16]:
Bilan=Bilan[~Bilan['Zone'].isin(['Chine - RAS de Hong-Kong', 'Chine - RAS de Macao','Chine, continentale','Chine, Taiwan Province de'])]
Bilan

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code Élément,Élément,Code Produit_y,Produit_y,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,511,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."

In [17]:
# les colonnes de tableau Bilan
Bilan.columns

Index(['Code zone_x', 'Zone', 'Code Produit_x', 'Produit_x', 'Année_x',
       'Origine', 'Aliments pour animaux',
       'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole'],
      dtype='object')

In [18]:
# Calcul de  Disponibilité alimentaires (en Kcal) pour l'ensemble de  population de chaque pays
Bilan['Disponibilité alimentaire (Kcal)']=Bilan['Disponibilité alimentaire (Kcal/personne/jour)']*365*Bilan['Valeur']*1000
Bilan

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Élément,Code Produit_y,Produit_y,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.086605e+09
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,Population totale,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00

In [19]:
# Calcul de Disponibilité de protéines en quantité (Kg) pour l'ensemble de  population de chaque pays

Bilan['Disponibilité de protéines en quantité (Kg)']=Bilan['Disponibilité de protéines en quantité (g/personne/jour)'] * Bilan['Valeur'] *0.001*365*1000
Bilan

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code Produit_y,Produit_y,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,0.000000e+00
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,1.086605e+04
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.086605e+09,2.173210e+04
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2501,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,5.170835e+06

# Question 4

In [20]:
# on va calculer pour chaque produit le ratio "énergie/poids", qu'on donnera en kcal/kg
Bilan['ratio_Energie_poid(kcal/kg)']=Bilan['Disponibilité alimentaire (Kcal)']/(Bilan ['Nourriture']*1e6)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [21]:
Bilan

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Produit_y,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,0.000000e+00,NaN
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,1.086605e+04,NaN
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.086605e+09,2.173210e+04,inf
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,Population,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00,NaN
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00,NaN
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,5.170835e+06,NaN

In [22]:
Bilan.columns

Index(['Code zone_x', 'Zone', 'Code Produit_x', 'Produit_x', 'Année_x',
       'Origine', 'Aliments pour animaux',
       'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)'],
      dtype='object')

In [23]:
# vérifier la cohérence de mon calcul en comparant ce ratio aux données disponibles sur internet 
# https://fr.wikipedia.org/wiki/%C5%92uf_(aliment)#Valeur_nutritionnelle
Bilan.loc [Bilan['Produit_x']=='Oeufs','ratio_Energie_poid(kcal/kg)']

74       1397.063571
144      1393.935000
226      1331.866750
319      1222.768481
400      1306.213333
            ...
15324    1329.968750
15416    1388.606000
15506    1424.751429
15596    1458.616842
15686    1468.041758
Name: ratio_Energie_poid(kcal/kg), Length: 171, dtype: float64

In [24]:
# Ensuite on va calculer le pourcentage de protéines de chaque produit 
Bilan['Pctage(poids_Port/poids_Total)']=Bilan['Disponibilité de protéines en quantité (Kg)']/(Bilan ['Nourriture']*1e6)*100

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [25]:
 Bilan

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,0.0,1024.0,130.60,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240
1,1,Arménie,2513,Orge,2013,vegetal,137.0,26.0,0.0,0.00,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,0.000000e+00,NaN,NaN
2,1,Arménie,2514,Maïs,2013,vegetal,96.0,NaN,0.0,0.03,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,0.000000e+00,1.086605e+04,NaN,inf
3,1,Arménie,2515,Seigle,2013,vegetal,1.0,NaN,1.0,0.12,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.086605e+09,2.173210e+04,inf,inf
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,351,Chine,2781,Huiles de Poissons,2013,animal,47.0,80.0,0.0,0.00,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00,NaN,NaN
15698,351,Chine,2782,Huiles de Foie de Poisso,2013,animal,0.0,0.0,0.0,0.00,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,0.000000e+00,NaN,NaN
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897
15701,351,Chine,2899,Miscellanees,2013,vegetal,NaN,NaN,0.0,NaN,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",0.000000e+00,5.170835e+06,NaN,NaN

In [26]:
# vérifier la cohérence de mon calcul en comparant ce ratio aux données disponibles sur internet 
#l'avoine en Pologne est de 8% https://fr.wikipedia.org/wiki/Avoine_cultiv%C3%A9e#Production
Avoine_Pologne=Bilan[(Bilan['Zone'] == 'Pologne') & (Bilan['Produit_x']=='Avoine')]
Avoine_Pologne

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
10996,173,Pologne,2516,Avoine,2013,vegetal,940.0,NaN,8.0,1.5,...,2013,2013,1000 personnes,38217,NaN,Donnée officielle,1.115936e+11,4463745.6,1957.783158,7.831133

# Question 5

In [27]:
# suppression des valeurs 0 et inf dans ratio_calorie_kcalperkg et ratio_protein_kprotperkg
# du Bilan pour ne pas fausser les calculs de la moyenne

Bilan = Bilan.replace([0, np.inf, -np.inf], np.nan).dropna(subset=["ratio_Energie_poid(kcal/kg)"], how="all")

Bilan = Bilan.replace([0, np.inf, -np.inf], np.nan).dropna(subset=["Pctage(poids_Port/poids_Total)"], how="all")

In [28]:
#on va d'abord groupe par produit en apllicant une moyenne 
Bilan_moyen=Bilan.groupby(['Produit_x']).mean()
Bilan_moyen

,Code zone_x,Code Produit_x,Année_x,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Code zone_y,Code Élément,Code Produit_y,Code année,Année_y,Valeur,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
Produit_x,,,,,,,,,,,,,,,,,,,,,
Abats Comestible,129.278481,2736.0,2013.0,84.083333,30.285714,8.398734,2.687595,0.250316,1.305000,111.303797,...,129.278481,511.0,2501.0,2013.0,2013.0,44270.183544,1.111792e+11,1.769276e+07,1130.422533,17.558732
"Agrumes, Autres",138.805556,2614.0,2013.0,NaN,12.000000,3.388889,4.866111,0.035000,0.057222,302.972222,...,138.805556,511.0,2501.0,2013.0,2013.0,63252.250000,6.886858e+10,1.305555e+06,248.435653,0.387735
Aliments pour enfants,128.555556,2680.0,2013.0,NaN,NaN,5.580247,0.549877,0.043951,0.229506,9.061728,...,128.555556,511.0,2501.0,2013.0,2013.0,35834.135802,3.383901e+10,1.380839e+06,3670.050309,14.874329
Ananas,122.490566,2618.0,2013.0,NaN,1.000000,5.698113,5.656887,0.023506,0.043208,217.716981,...,122.490566,511.0,2501.0,2013.0,2013.0,55101.849057,6.530468e+10,5.112861e+05,417.217377,0.308420
Animaux Aquatiques Autre,228.000000,2769.0,2013.0,NaN,NaN,1.000000,0.880000,0.010000,0.093333,357.666667,...,228.000000,511.0,2501.0,2013.0,2013.0,510980.333333,1.865078e+11,1.362626e+07,451.948298,3.827255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Viande de Suides,125.650685,2733.0,2013.0,NaN,16.625000,96.630137,15.699795,8.625137,4.357329,770.890411,...,125.650685,511.0,2501.0,2013.0,2013.0,41278.020548,2.176974e+12,8.125097e+07,2534.081690,10.279412
Viande de Volailles,126.883041,2734.0,2013.0,NaN,40.612903,73.479532,20.204386,4.823333,7.022398,625.578947,...,126.883041,511.0,2501.0,2013.0,2013.0,40920.035088,8.777017e+11,7.704491e+07,1299.811793,12.626174
"Viande, Autre",136.945946,2735.0,2013.0,7.000000,5.000000,9.072072,2.684595,0.387117,1.286486,60.651376,...,136.945946,511.0,2501.0,2013.0,2013.0,37969.135135,7.236932e+10,1.047986e+07,1294.463333,17.427852
Vin,256.000000,2655.0,2013.0,NaN,NaN,100.000000,51.410000,NaN,0.010000,27.000000,...,256.000000,511.0,2501.0,2013.0,2013.0,530.000000,1.934500e+10,1.934500e+03,716.481481,0.007165
"Épices, Autres",129.972973,2645.0,2013.0,NaN,36.200000,7.126126,0.752703,0.256577,0.228468,48.690909,...,129.972973,511.0,2501.0,2013.0,2013.0,58770.594595,1.506672e+11,4.921370e+06,3492.904538,10.710053

In [29]:
#trier par odres décroissant 
Bilan_moyen_trier=Bilan_moyen.sort_values(by = 'ratio_Energie_poid(kcal/kg)', ascending=[False])
Bilan_moyen_trier

,Code zone_x,Code Produit_x,Année_x,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Code zone_y,Code Élément,Code Produit_y,Code année,Année_y,Valeur,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
Produit_x,,,,,,,,,,,,,,,,,,,,,
Huil Plantes Oleif Autr,113.586207,2586.0,2013.0,NaN,14.818182,33.810345,1.423103,3.804483,0.026379,21.258621,...,113.586207,511.0,2501.0,2013.0,2013.0,11111.620690,9.738184e+10,9.686804e+04,9210.957320,1.128100
Huile d'Arachide,255.000000,2572.0,2013.0,NaN,2.000000,9.000000,0.360000,0.990000,0.010000,6.000000,...,255.000000,511.0,2501.0,2013.0,2013.0,11104.000000,3.647664e+10,4.052960e+04,9119.160000,1.013240
Huile de Tournesol,117.157895,2573.0,2013.0,NaN,56.294118,198.157895,8.181053,22.381053,0.045263,304.789474,...,117.157895,511.0,2501.0,2013.0,2013.0,26639.473684,2.233419e+12,4.529264e+05,8828.241740,0.284951
Huile de Germe de Maïs,39.000000,2582.0,2013.0,NaN,41.000000,101.000000,4.265000,11.350000,0.075000,45.000000,...,39.000000,511.0,2501.0,2013.0,2013.0,6960.500000,2.112313e+11,1.597386e+05,8720.597381,0.749458
Huile de Soja,129.400000,2571.0,2013.0,NaN,245.947368,149.920000,6.333600,16.920800,0.052000,695.920000,...,129.400000,511.0,2501.0,2013.0,2013.0,42505.680000,4.262362e+12,1.188547e+06,8615.155413,0.320761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pamplemousse,137.492063,2613.0,2013.0,NaN,1.200000,4.285714,7.247937,0.041923,0.061111,129.904762,...,137.492063,511.0,2501.0,2013.0,2013.0,49567.809524,3.204741e+10,4.664401e+05,249.722290,0.331530
"Agrumes, Autres",138.805556,2614.0,2013.0,NaN,12.000000,3.388889,4.866111,0.035000,0.057222,302.972222,...,138.805556,511.0,2501.0,2013.0,2013.0,63252.250000,6.886858e+10,1.305555e+06,248.435653,0.387735
"Mollusques, Autres",139.277778,2767.0,2013.0,19.0,7.666667,2.000000,3.448889,0.031667,0.278889,478.750000,...,139.277778,511.0,2501.0,2013.0,2013.0,77436.750000,8.468968e+10,1.196207e+07,243.388299,3.086989
Tomates,126.920530,2601.0,2013.0,935.0,12.833333,10.721854,20.430464,0.122933,0.511457,1055.649007,...,126.920530,511.0,2501.0,2013.0,2013.0,44080.298013,1.793555e+11,9.152320e+06,205.450549,0.954899
Citrons & Limes,128.988636,2612.0,2013.0,NaN,7.000000,1.852273,3.746818,0.031839,0.042159,173.340909,...,128.988636,511.0,2501.0,2013.0,2013.0,55727.897727,3.053745e+10,6.887775e+05,195.738548,0.431402

In [30]:
#selection de 5 premiers produits de ration energie et poids 
Bilan_moyen_trier["ratio_Energie_poid(kcal/kg)"][0:5]

Produit_x
Huil Plantes Oleif Autr    9210.957320
Huile d'Arachide           9119.160000
Huile de Tournesol         8828.241740
Huile de Germe de Maïs     8720.597381
Huile de Soja              8615.155413
Name: ratio_Energie_poid(kcal/kg), dtype: float64

In [31]:
#trier les par rapport au plus riche en protéine 
Bilan_moyen_trier=Bilan_moyen.sort_values(by = 'Pctage(poids_Port/poids_Total)', ascending=[False])
Bilan_moyen_trier

,Code zone_x,Code Produit_x,Année_x,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Code zone_y,Code Élément,Code Produit_y,Code année,Année_y,Valeur,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
Produit_x,,,,,,,,,,,,,,,,,,,,,
Soja,125.859649,2555.0,2013.0,744.533333,75.750000,16.175439,1.734386,0.711053,1.606140,2624.754386,...,125.859649,511.0,2501.0,2013.0,2013.0,83396.684211,6.322670e+11,6.025331e+07,3311.134447,33.134374
Graines Colza/Moutarde,33.000000,2558.0,2013.0,739.000000,NaN,16.000000,1.000000,1.000000,1.000000,8098.000000,...,33.000000,511.0,2501.0,2013.0,2013.0,35182.000000,2.054629e+11,1.284143e+07,4565.841778,28.536511
Arachides Decortiquees,131.172932,2556.0,2013.0,1.000000,158.125000,25.714286,1.700977,2.132857,1.120451,220.571429,...,131.172932,511.0,2501.0,2013.0,2013.0,48401.172932,4.872190e+11,2.108807e+07,5706.928520,25.180390
Pois,136.577982,2547.0,2013.0,109.900000,14.000000,12.146789,1.298165,0.064752,0.796239,95.412844,...,136.577982,511.0,2501.0,2013.0,2013.0,55738.880734,1.780572e+11,1.188242e+07,3475.637480,22.287650
Légumineuses Autres,128.897638,2549.0,2013.0,128.979592,90.666667,37.637795,4.016614,0.259200,2.414409,300.322835,...,128.897638,511.0,2501.0,2013.0,2013.0,52003.299213,7.424157e+11,4.526852e+07,3426.751230,21.870861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Huile de Tournesol,117.157895,2573.0,2013.0,NaN,56.294118,198.157895,8.181053,22.381053,0.045263,304.789474,...,117.157895,511.0,2501.0,2013.0,2013.0,26639.473684,2.233419e+12,4.529264e+05,8828.241740,0.284951
"Sucre, canne",121.160000,2536.0,2013.0,1736.666667,70106.400000,11.480000,14.502000,0.081111,0.066800,52666.520000,...,121.160000,511.0,2501.0,2013.0,2013.0,95402.360000,3.777076e+11,1.817453e+06,294.221088,0.202011
Pommes,124.552632,2617.0,2013.0,39.000000,10.250000,15.245614,14.200351,0.086460,0.067456,733.327434,...,124.552632,511.0,2501.0,2013.0,2013.0,48399.394737,2.597354e+11,1.474511e+06,401.087981,0.188116
Edulcorants Autres,138.470588,2543.0,2013.0,NaN,179.916667,66.823529,8.606471,0.043333,0.037059,1034.117647,...,138.470588,511.0,2501.0,2013.0,2013.0,67200.352941,2.784776e+12,1.884031e+06,2844.620817,0.171495
Vin,256.000000,2655.0,2013.0,NaN,NaN,100.000000,51.410000,NaN,0.010000,27.000000,...,256.000000,511.0,2501.0,2013.0,2013.0,530.000000,1.934500e+10,1.934500e+03,716.481481,0.007165

In [32]:
#selection de 5 premiers parmis les plus riche en protéine  
Bilan_moyen_trier["Pctage(poids_Port/poids_Total)"][0:5]

Produit_x
Soja                      33.134374
Graines Colza/Moutarde    28.536511
Arachides Decortiquees    25.180390
Pois                      22.287650
Légumineuses Autres       21.870861
Name: Pctage(poids_Port/poids_Total), dtype: float64

# Question 6

In [33]:
#on va d'abord selectionner que les produits vegetaux
Bilan_Vege=Bilan[Bilan["Origine"]=='vegetal']
Bilan_Vege

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15670,351,Chine,2645,"Épices, Autres",2013,vegetal,NaN,NaN,1.0,0.15,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,2.068334e+07,2405.039326,9.620157
15672,351,Chine,2656,Bière,2013,vegetal,NaN,9.0,49.0,36.29,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",2.533709e+13,2.585417e+08,492.901122,0.502960
15673,351,Chine,2657,Boissons Fermentés,2013,vegetal,NaN,NaN,3.0,1.97,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",1.551250e+12,5.170835e+06,556.003715,0.185335
15676,351,Chine,2680,Aliments pour enfants,2013,vegetal,NaN,NaN,1.0,0.09,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,2.068334e+07,3917.298902,15.669196
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045

In [34]:
#on va aussi change les dispo inter en Kcal en multipliant par 1e6 car il était en tonnes 
Dispo_inter_mondial_veget_kcal=(Bilan_Vege['Disponibilité intérieure']*1e6 *Bilan_Vege['ratio_Energie_poid(kcal/kg)']).sum()

In [35]:
Dispo_inter_mondial_veget_kcal

1.043053783146984e+16

# Question 7

In [36]:
#nombre des humains qui peuvent être nourris selon la disponibilité alimentaire mondiale 
#l'homme en calories a besoin de 2500 Kcal/jour selon Wikipedia
#https://fr.wikipedia.org/wiki/Ration_alimentaire#:~:text=pour%20un%20homme%20entre%2018%20et%2040%20ans%20(actif)%20%3A,(active)%20%3A%202%20200%20kcal
nombrehumains=Dispo_inter_mondial_veget_kcal/(2500*365)
nombrehumains

11430726390.65188

In [37]:
#pour voir le pourcentage de la population mondiale 
Pourcentage_Mondial = ((nombrehumains/9700000000)*100)
round(Pourcentage_Mondial,2)

117.84

In [38]:
#on va aussi change les dispo inter en Kg de proteine en multipliant par 1e6 car il était en milliers de tonnes 
Dispo_inter_mondial_proteine_kg=(Bilan_Vege['Disponibilité intérieure']*1e6 *Bilan_Vege['Pctage(poids_Port/poids_Total)']/100).sum()
Dispo_inter_mondial_proteine_kg

276747137158.94324

In [39]:
#nombre des humains qui peuvent être nourris selon la disponibilité alimentaire mondiale 
#l'homme en calories a besoin de 75g/kg /jour selon Wikipedia 
#https://fr.wikipedia.org/wiki/Ration_alimentaire#R%C3%A9partition_des_diff%C3%A9rents_nutriments
nombrehumains2=Dispo_inter_mondial_proteine_kg/(75e-3*365)
nombrehumains2

10109484462.42715

In [40]:
#pour voir le pourcentage de la population mondiale 
Pourcentage_Mondial2 = (nombrehumains2/Population_Mondiale)*100
round(Pourcentage_Mondial2,2)

144.48

# QUESTION 8

In [41]:
Bilan_Vege.columns

Index(['Code zone_x', 'Zone', 'Code Produit_x', 'Produit_x', 'Année_x',
       'Origine', 'Aliments pour animaux',
       'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)', 'Pctage(poids_Port/poids_Total)'],
      dtype='object')

In [42]:
#en terme d'energie
Total_kcal= Bilan_Vege[['Aliments pour animaux','Nourriture','Pertes']].sum(axis=1)
Total_kcal=(Total_kcal*Bilan_Vege['ratio_Energie_poid(kcal/kg)']*1e6).sum()

In [43]:
#nombres humain qu'on peut nourrire si les vegetaux animal et perte utiliser poue alimentation humaine
nombre_humain=Total_kcal/(2500*365)
nombre_humain

8854870463.511135

In [44]:
#résultats en pourcentage de la population mondiale
pourcentage=(nombre_humain/Population_Mondiale)*100
pourcentage

126.54649023800143

In [45]:
#en terme de protéine 
Total_Proteine= Bilan_Vege[['Aliments pour animaux','Nourriture','Pertes']].sum(axis=1)
Total_Proteine= (Total_Proteine*Bilan_Vege['Pctage(poids_Port/poids_Total)']*1e4).sum()
Total_Proteine

202198629145.0782

In [46]:
#nombres humain qu'on peut nourrire avec proteines
nombre_humain2=Total_Proteine/(0.75e-3*60*365)
nombre_humain2

12310418821.618155

In [47]:
#résultats en pourcentage de la population mondiale
pourcentage2=(nombre_humain2/Population_Mondiale)*100
round(pourcentage2,2)

175.93

# Question 9

In [48]:
Bilan

,Code zone_x,Zone,Code Produit_x,Produit_x,Année_x,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15694,351,Chine,2767,"Mollusques, Autres",2013,animal,NaN,NaN,4.0,8.85,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",2.068334e+12,2.895667e+08,164.978370,2.309697
15695,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,NaN,NaN,1.0,0.67,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,3.619584e+07,542.584948,3.798095
15696,351,Chine,2775,Plantes Aquatiques,2013,animal,NaN,20.0,9.0,9.24,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.653751e+12,3.567876e+08,355.628236,2.726483
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897

In [49]:
#disponibilité alimentaire en calories
Dispo_alim_monde_cal=(Bilan['Nourriture'] *Bilan ['ratio_Energie_poid(kcal/kg)']*1e6).sum()
Dispo_alim_monde_cal

6246443741770000.0

In [50]:
# Nombre de la population nourri par la disponibilité alimentaire mondiale car un homme à besoin de 2500kcal par jour
Nombre_humain_cal=Dispo_alim_monde_cal/(2500*365)
Nombre_humain_cal

6845417799.2

In [51]:
# pourcentage par rapport au nombre de humains que 
pourcentage3=(Nombre_humain_cal/Population_Mondiale)*100
round(pourcentage3,2)

97.83

In [52]:
# disponibilité de pro
Dispo_alim_monde_proteine=(Bilan['Nourriture'] *Bilan ['Pctage(poids_Port/poids_Total)']*1e4).sum()
Dispo_alim_monde_proteine

206807631925.25

In [53]:
Nombre_humain_prot=Dispo_alim_monde_proteine/17.68
Nombre_humain_prot

11697264249.165724

In [54]:
# pourcentage par rapport au nombre de humains qu'on peut nourrire avec autant de protéine  
pourcentage4=(Nombre_humain_prot/Population_Mondiale)*100
round(pourcentage4,2)

167.17

# Question 10

In [55]:
# lecture de tableau ceréales
ceréales = pd.read_csv('fr_ceréales.csv')
ceréales

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2805,Riz (Eq Blanchi),2013,2013,Milliers de tonnes,342,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2513,Orge,2013,2013,Milliers de tonnes,514,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,312,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,13,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,799,S,Données standardisées
887,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2516,Avoine,2013,2013,Milliers de tonnes,1,S,Données standardisées
888,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,55,S,Données standardisées
889,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2518,Sorgho,2013,2013,Milliers de tonnes,69,S,Données standardisées
890,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2520,"Céréales, Autres",2013,2013,Milliers de tonnes,2,S,Données standardisées

In [56]:
ceréales.sort_values(by=['Code Produit','Produit'],ascending=True)
for index,row in ceréales.iterrows():
    print(row['Code Produit'],row['Produit'])

2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2514 Maïs
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2516 Avoine
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2514 Maïs
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2516 Avoine
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2517 Millet
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2517 Millet
2518 Sorgho
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2511 Blé
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2805 Riz (Eq Blanchi)
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2513 Orge
2515 Seigle
2516 Avoine
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)

2514 Maïs
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2805 Riz (Eq Blanchi)
2514 Maïs
2511 Blé
2513 Orge
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2515 Seigle
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2518 Sorgho
2520 Céréales, Autres
2514 Maïs
2511 Blé
2805 Riz (Eq Blanchi)
2514 Maïs
2518 Sorgho
2805 Riz (Eq Blanchi)
2514 Maïs
2517 Millet
2511 Blé
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2517 Millet
2518 Sorgho
2511 Blé
2805 Riz (Eq Blanchi)
2513 Orge
2514 Maïs
2516 Avoine
2517 Millet
2518 Sorgho
2520 Céréales, Autres

In [57]:
# renomer les colonnes de Bilan 
Bilan.rename(columns={'Code zone_x': 'Code zone', 'Code Produit_x': 'Code Produit', 'Produit_x': 'Produit','Année_x':'Année'}, inplace=True)
Bilan

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Code année,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total)
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,2013,2013,1000 personnes,2977,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15694,351,Chine,2767,"Mollusques, Autres",2013,animal,NaN,NaN,4.0,8.85,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",2.068334e+12,2.895667e+08,164.978370,2.309697
15695,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,NaN,NaN,1.0,0.67,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,3.619584e+07,542.584948,3.798095
15696,351,Chine,2775,Plantes Aquatiques,2013,animal,NaN,20.0,9.0,9.24,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.653751e+12,3.567876e+08,355.628236,2.726483
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897

In [58]:
# on afficher d'abord le tableaux de population sous alimentattion 
Sous_alimentation = pd.read_csv('fr_sousalimentation.csv')
Sous_alimentation

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6.6,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN
1017,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,7.8,F,Estimation FAO,NaN
1018,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,8.2,F,Estimation FAO,NaN
1019,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,8.5,F,Estimation FAO,NaN

In [59]:
# trier selon les pays
#selectionne la periode 2013-2015
Sous_alimentation.sort_values(by=['Zone'])
Sous_alimentation_t=Sous_alimentation[Sous_alimentation["Année"]=="2013-2015"]
Sous_alimentation_t

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
6,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,2.8,F,Estimation FAO,NaN
11,FS,Données de la sécurité alimentaire,3,Albanie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,0.2,F,Estimation FAO,NaN
16,FS,Données de la sécurité alimentaire,4,Algérie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,1.6,F,Estimation FAO,NaN
21,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,NaN,NR,Non rapportée,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,FS,Données de la sécurité alimentaire,236,Venezuela (République bolivarienne du),6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,2.9,F,Estimation FAO,NaN
1001,FS,Données de la sécurité alimentaire,237,Viet Nam,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,9.7,F,Estimation FAO,NaN
1006,FS,Données de la sécurité alimentaire,249,Yémen,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.2,F,Estimation FAO,NaN
1011,FS,Données de la sécurité alimentaire,251,Zambie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN

In [60]:
Sous_alimentation.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole', 'Note'],
      dtype='object')

In [61]:
# verification s'il ya pas des pays de plus qui peuvent donner les mauvais résultat(les redondances) 
# Visualisation des tous les pays
for index,row in Sous_alimentation_t.iterrows():
    print(row['Code zone'],row['Zone'])

2 Afghanistan
202 Afrique du Sud
3 Albanie
4 Algérie
79 Allemagne
6 Andorre
7 Angola
8 Antigua-et-Barbuda
194 Arabie saoudite
9 Argentine
1 Arménie
10 Australie
11 Autriche
52 Azerbaïdjan
12 Bahamas
13 Bahreïn
16 Bangladesh
14 Barbade
57 Bélarus
255 Belgique
23 Belize
53 Bénin
17 Bermudes
18 Bhoutan
19 Bolivie (État plurinational de)
80 Bosnie-Herzégovine
20 Botswana
21 Brésil
26 Brunéi Darussalam
27 Bulgarie
233 Burkina Faso
29 Burundi
35 Cabo Verde
115 Cambodge
32 Cameroun
33 Canada
40 Chili
351 Chine
96 Chine - RAS de Hong-Kong
128 Chine - RAS de Macao
41 Chine, continentale
214 Chine, Taiwan Province de
50 Chypre
44 Colombie
45 Comores
46 Congo
48 Costa Rica
107 Côte d'Ivoire
98 Croatie
49 Cuba
54 Danemark
72 Djibouti
55 Dominique
59 Égypte
60 El Salvador
225 Émirats arabes unis
58 Équateur
178 Érythrée
203 Espagne
63 Estonie
209 Eswatini
231 États-Unis d'Amérique
238 Éthiopie
185 Fédération de Russie
66 Fidji
67 Finlande
68 France
74 Gabon
75 Gambie
73 Géorgie
81 Ghana
84 Grèce
86 Grenade
85 Groenland
89 Guatemala
90 Guinée
61 Guinée équatoriale
175 Guinée-Bissau
91 Guyana
93 Haïti
95 Honduras
97 Hongrie
47 Îles Cook
127 Îles Marshall
25 Îles Salomon
100 Inde
101 Indonésie
102 Iran (République islamique d')
103 Iraq
104 Irlande
99 Islande
105 Israël
106 Italie
109 Jamaïque
110 Japon
112 Jordanie
108 Kazakhstan
114 Kenya
113 Kirghizistan
83 Kiribati
118 Koweït
122 Lesotho
119 Lettonie
121 Liban
123 Libéria
124 Libye
126 Lituanie
256 Luxembourg
154 Macédoine du Nord
129 Madagascar
131 Malaisie
130 Malawi
132 Maldives
133 Mali
134 Malte
143 Maroc
137 Maurice
136 Mauritanie
138 Mexique
145 Micronésie (États fédérés de)
141 Mongolie
273 Monténégro
144 Mozambique
28 Myanmar
147 Namibie
148 Nauru
149 Népal
157 Nicaragua
158 Niger
159 Nigéria
160 Nioué
162 Norvège
153 Nouvelle-Calédonie
156 Nouvelle-Zélande
221 Oman
226 Ouganda
235 Ouzbékistan
165 Pakistan
180 Palaos
299 Palestine
166 Panama
168 Papouasie-Nouvelle-Guinée
169 Paraguay
150 Pays-Bas
170 Pérou
171 Philippines
173 Pologne
70 Polynésie française
177 Porto Rico
174 Portugal
179 Qatar
212 République arabe syrienne
37 République centrafricaine
117 République de Corée
146 République de Moldova
250 République démocratique du Congo
120 République démocratique populaire lao
56 République dominicaine
116 République populaire démocratique de Corée
215 République-Unie de Tanzanie
183 Roumanie
229 Royaume-Uni
184 Rwanda
189 Sainte-Lucie
188 Saint-Kitts-et-Nevis
191 Saint-Vincent-et-les Grenadines
244 Samoa
5 Samoa américaines
193 Sao Tomé-et-Principe
195 Sénégal
272 Serbie
196 Seychelles
197 Sierra Leone
200 Singapour
199 Slovaquie
198 Slovénie
201 Somalie
276 Soudan
277 Soudan du Sud
38 Sri Lanka
210 Suède
211 Suisse
207 Suriname
208 Tadjikistan
39 Tchad
167 Tchéquie (la)
216 Thaïlande
176 Timor-Leste
217 Togo
218 Tokélaou
219 Tonga
220 Trinité-et-Tobago
222 Tunisie
213 Turkménistan
223 Turquie
227 Tuvalu
230 Ukraine
234 Uruguay
155 Vanuatu
236 Venezuela (République bolivarienne du)
237 Viet Nam
249 Yémen
251 Zambie
181 Zimbabwe

In [62]:
#on remarque que la chine a plusieurs données ,on va suprime les provinces de la chine 
Sous_alimentation_finale=Sous_alimentation_t[~Sous_alimentation_t['Zone'].isin(['Chine - RAS de Hong-Kong', 'Chine - RAS de Macao','Chine, continentale','Chine, Taiwan Province de'])]
Sous_alimentation_finale

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
6,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,2.8,F,Estimation FAO,NaN
11,FS,Données de la sécurité alimentaire,3,Albanie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,0.2,F,Estimation FAO,NaN
16,FS,Données de la sécurité alimentaire,4,Algérie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,1.6,F,Estimation FAO,NaN
21,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,NaN,NR,Non rapportée,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,FS,Données de la sécurité alimentaire,236,Venezuela (République bolivarienne du),6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,2.9,F,Estimation FAO,NaN
1001,FS,Données de la sécurité alimentaire,237,Viet Nam,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,9.7,F,Estimation FAO,NaN
1006,FS,Données de la sécurité alimentaire,249,Yémen,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.2,F,Estimation FAO,NaN
1011,FS,Données de la sécurité alimentaire,251,Zambie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN

In [63]:
#ici on va remplacer nan par 0 et <0.1 par 0.  
Sous_alimentation_finale['Valeur']= Sous_alimentation_finale['Valeur'].replace(["nan ", "<0.1"], "0")
# Et on va formater le tableau pour pouvoir faire la somme 
Sous_alimentation_finale['Valeur']=Sous_alimentation_finale['Valeur'].astype(float)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [64]:
#Calculer de nombre des humains sous alimenation 
Population_Sous_alimentation_Mondiale = Sous_alimentation_finale['Valeur'].sum()*1000000
Population_Sous_alimentation_Mondiale

735200000.0

In [65]:
# la proportion de la population mondiale est considérée comme étant en sous-nutrition en pourcentage entre 2013-2015
Prcentage= (Population_Sous_alimentation_Mondiale/Population_Mondiale)*100
round(Prcentage,2)

10.51

In [66]:
# Ajouter la colonne is-cereal
Bilan['is_cereal']= Bilan['Produit'].isin(ceréales['Produit'])
Bilan

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Année_y,Unité,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2013,1000 personnes,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240,True
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2013,1000 personnes,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445,True
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2013,1000 personnes,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933,True
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,2013,1000 personnes,2977,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145,False
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,2013,1000 personnes,2977,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15694,351,Chine,2767,"Mollusques, Autres",2013,animal,NaN,NaN,4.0,8.85,...,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",2.068334e+12,2.895667e+08,164.978370,2.309697,False
15695,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,NaN,NaN,1.0,0.67,...,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,3.619584e+07,542.584948,3.798095,False
15696,351,Chine,2775,Plantes Aquatiques,2013,animal,NaN,20.0,9.0,9.24,...,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.653751e+12,3.567876e+08,355.628236,2.726483,False
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045,True
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897,False

# Question 11

In [67]:
# En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale)
# quelle proportion (en termes de poids) est destinée à l'alimentation animale ?
Bilan[['Valeur_cereal','Unite_cereal']]= ceréales[['Valeur','Unité']]
Bilan

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240,True,5169.0,Milliers de tonnes
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445,True,13.0,Milliers de tonnes
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933,True,268.0,Milliers de tonnes
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,2977,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145,False,11811.0,Milliers de tonnes
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,2977,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235,False,372.0,Milliers de tonnes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15694,351,Chine,2767,"Mollusques, Autres",2013,animal,NaN,NaN,4.0,8.85,...,1416667,A,"Agrégat, peut inclure des données officielles,...",2.068334e+12,2.895667e+08,164.978370,2.309697,False,NaN,NaN
15695,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,NaN,NaN,1.0,0.67,...,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,3.619584e+07,542.584948,3.798095,False,NaN,NaN
15696,351,Chine,2775,Plantes Aquatiques,2013,animal,NaN,20.0,9.0,9.24,...,1416667,A,"Agrégat, peut inclure des données officielles,...",4.653751e+12,3.567876e+08,355.628236,2.726483,False,NaN,NaN
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045,True,NaN,NaN
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,1416667,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897,False,NaN,NaN

In [68]:
# selection que le produit ceréale
F_ceréales= Bilan [Bilan ['is_cereal']==True] 
F_ceréales

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,2977,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240,True,5169.0,Milliers de tonnes
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,2977,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445,True,13.0,Milliers de tonnes
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,2977,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933,True,268.0,Milliers de tonnes
87,1,Arménie,2805,Riz (Eq Blanchi),2013,vegetal,NaN,NaN,34.0,3.18,...,2977,NaN,Donnée officielle,3.694457e+10,7.171593e+05,4104.952222,7.968437,True,1255.0,Milliers de tonnes
90,2,Afghanistan,2511,Blé,2013,vegetal,NaN,NaN,1369.0,160.23,...,30552,NaN,Donnée officielle,1.526638e+13,4.116011e+08,3118.769381,8.408603,True,1485.0,Milliers de tonnes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15609,351,Chine,2516,Avoine,2013,vegetal,500.0,NaN,1.0,0.15,...,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,1.551250e+07,2405.039326,7.215118,True,NaN,NaN
15610,351,Chine,2517,Millet,2013,vegetal,800.0,NaN,5.0,0.59,...,1416667,A,"Agrégat, peut inclure des données officielles,...",2.585417e+12,6.205001e+07,3100.020713,7.440050,True,NaN,NaN
15611,351,Chine,2518,Sorgho,2013,vegetal,1998.0,24.0,10.0,1.31,...,1416667,A,"Agrégat, peut inclure des données officielles,...",5.170835e+12,1.499542e+08,2787.511887,8.083784,True,NaN,NaN
15612,351,Chine,2520,"Céréales, Autres",2013,vegetal,661.0,NaN,2.0,0.29,...,1416667,A,"Agrégat, peut inclure des données officielles,...",1.034167e+12,3.102501e+07,2553.498543,7.660496,True,NaN,NaN
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,1416667,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045,True,NaN,NaN

In [69]:
#proportion de céréale animal 
proportion=(F_ceréales["Aliments pour animaux"].sum()/(F_ceréales["Aliments pour animaux"].sum()+F_ceréales["Nourriture"].sum()))*100
round(proportion,2)

44.47

In [70]:
# Pays sous nutristion
Bilan.sort_values(by ='Zone')
Bilan['Pays_est_SousNutrition']=Sous_alimentation['Zone'].isin(Bilan['Zone'])
Bilan

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition
0,1,Arménie,2511,Blé,2013,vegetal,93.0,NaN,1024.0,130.60,...,NaN,Donnée officielle,1.112684e+12,3.316318e+07,2860.368946,8.525240,True,5169.0,Milliers de tonnes,True
4,1,Arménie,2516,Avoine,2013,vegetal,4.0,NaN,2.0,0.37,...,NaN,Donnée officielle,2.173210e+09,9.779445e+04,2173.210000,9.779445,True,13.0,Milliers de tonnes,True
7,1,Arménie,2520,"Céréales, Autres",2013,vegetal,1.0,12.0,14.0,1.96,...,NaN,Donnée officielle,1.521247e+10,4.237760e+05,2535.411667,7.062933,True,268.0,Milliers de tonnes,True
8,1,Arménie,2531,Pommes de Terre,2013,vegetal,225.0,16.0,82.0,45.10,...,NaN,Donnée officielle,8.910161e+10,2.108014e+06,664.937388,1.573145,False,11811.0,Milliers de tonnes,True
17,1,Arménie,2551,Noix,2013,vegetal,NaN,NaN,18.0,2.15,...,NaN,Donnée officielle,1.955889e+10,4.563741e+05,3259.815000,7.606235,False,372.0,Milliers de tonnes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15694,351,Chine,2767,"Mollusques, Autres",2013,animal,NaN,NaN,4.0,8.85,...,A,"Agrégat, peut inclure des données officielles,...",2.068334e+12,2.895667e+08,164.978370,2.309697,False,NaN,NaN,NaN
15695,351,Chine,2769,Animaux Aquatiques Autre,2013,animal,NaN,NaN,1.0,0.67,...,A,"Agrégat, peut inclure des données officielles,...",5.170835e+11,3.619584e+07,542.584948,3.798095,False,NaN,NaN,NaN
15696,351,Chine,2775,Plantes Aquatiques,2013,animal,NaN,20.0,9.0,9.24,...,A,"Agrégat, peut inclure des données officielles,...",4.653751e+12,3.567876e+08,355.628236,2.726483,False,NaN,NaN,NaN
15699,351,Chine,2805,Riz (Eq Blanchi),2013,vegetal,12117.0,2085.0,797.0,77.45,...,A,"Agrégat, peut inclure des données officielles,...",4.121155e+14,7.482198e+09,3755.894405,6.819045,True,NaN,NaN,NaN
15700,351,Chine,2848,Lait - Excl Beurre,2013,animal,1632.0,42.0,59.0,33.18,...,A,"Agrégat, peut inclure des données officielles,...",3.050792e+13,1.613300e+09,648.980490,3.431897,False,NaN,NaN,NaN

In [71]:
#
top15_expor=Bilan.loc[Bilan['Pays_est_SousNutrition']==True,("Produit","Exportations - Quantité","Pays_est_SousNutrition")]
top15_expor

                  Produit  Exportations - Quantité Pays_est_SousNutrition
0                     Blé                      1.0                   True
4                  Avoine                      NaN                   True
7        Céréales, Autres                      NaN                   True
8         Pommes de Terre                      9.0                   True
17                   Noix                      1.0                   True
...                   ...                      ...                    ...
991                  Soja                      NaN                   True
1014              Tomates                      NaN                   True
1015              Oignons                      NaN                   True
1016      Légumes, Autres                      8.0                   True
1017  Oranges, Mandarines                      2.0                   True

[377 rows x 3 columns]

In [72]:
# top 15 produits les plus exporte  dans les pays sous nutrition
top15_export_produit=top15_expor['Produit'][:15].tolist()
top15_export_produit

['Blé',
 'Avoine',
 'Céréales, Autres',
 'Pommes de Terre',
 'Noix',
 'Arachides Decortiquees',
 'Olives',
 'Tomates',
 'Oignons',
 'Légumes, Autres',
 'Oranges, Mandarines',
 'Bananes',
 'Bananes plantains',
 'Pommes',
 'Raisin']

In [73]:
# 200 plus grand importation
Bilan['Top15_Produit'] = Bilan['Produit'].isin(top15_export_produit)
Top200=Bilan[Bilan['Top15_Produit']== True] 
Top200=Top200.sort_values(by='Importations - Quantité',ascending=False)[:200]
Top200

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit
3674,59,Égypte,2511,Blé,2013,vegetal,4860.0,NaN,1175.0,146.83,...,Donnée officielle,3.519177e+13,1.066835e+09,2920.963396,8.854869,True,NaN,NaN,NaN,True
1333,21,Brésil,2511,Blé,2013,vegetal,600.0,1.0,384.0,53.00,...,Donnée officielle,2.808274e+13,7.459477e+08,2644.325605,7.023990,True,NaN,NaN,NaN,True
15605,351,Chine,2511,Blé,2013,vegetal,26694.0,2948.0,546.0,63.10,...,"Agrégat, peut inclure des données officielles,...",2.823276e+14,8.997252e+09,3158.521093,10.065617,True,NaN,NaN,NaN,True
6128,101,Indonésie,2511,Blé,2013,vegetal,202.0,155.0,183.0,25.45,...,Donnée officielle,1.668980e+13,4.459733e+08,2624.182307,7.012159,True,NaN,NaN,NaN,True
14308,231,États-Unis d'Amérique,2605,"Légumes, Autres",2013,vegetal,193.0,NaN,43.0,66.66,...,Donnée officielle,5.023200e+12,2.383100e+08,235.455163,1.117043,False,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,10,Australie,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,52.0,63.09,...,Donnée officielle,4.430501e+11,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True
5566,95,Honduras,2511,Blé,2013,vegetal,6.0,NaN,294.0,37.36,...,Donnée officielle,8.687818e+11,2.207415e+07,2876.760795,7.309321,True,NaN,NaN,NaN,True
4904,81,Ghana,2601,Tomates,2013,vegetal,NaN,NaN,16.0,26.07,...,Donnée officielle,1.512852e+11,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True
12055,194,Arabie saoudite,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,45.0,63.07,...,Donnée officielle,4.735163e+11,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True
9626,150,Pays-Bas,2556,Arachides Decortiquees,2013,vegetal,NaN,NaN,18.0,1.15,...,Donnée officielle,1.101066e+11,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True

In [74]:
Top200.columns

Index(['Code zone', 'Zone', 'Code Produit', 'Produit', 'Année', 'Origine',
       'Aliments pour animaux', 'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)', 'Pctage(poids_Port/poids_Total)',
       'is_cereal', 'Valeur_cereal', 'Unite_cereal', 'Pays_est_SousNutrition',
       'Top15_Produit'],
      dtype='object')

In [75]:
#le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.
Top200 ["Ration_quanti_inter"]=Top200["Autres utilisations (non alimentaire)"]/Top200["Disponibilité intérieure"]
Top200

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit,Ration_quanti_inter
3674,59,Égypte,2511,Blé,2013,vegetal,4860.0,NaN,1175.0,146.83,...,3.519177e+13,1.066835e+09,2920.963396,8.854869,True,NaN,NaN,NaN,True,NaN
1333,21,Brésil,2511,Blé,2013,vegetal,600.0,1.0,384.0,53.00,...,2.808274e+13,7.459477e+08,2644.325605,7.023990,True,NaN,NaN,NaN,True,0.000083
15605,351,Chine,2511,Blé,2013,vegetal,26694.0,2948.0,546.0,63.10,...,2.823276e+14,8.997252e+09,3158.521093,10.065617,True,NaN,NaN,NaN,True,0.023221
6128,101,Indonésie,2511,Blé,2013,vegetal,202.0,155.0,183.0,25.45,...,1.668980e+13,4.459733e+08,2624.182307,7.012159,True,NaN,NaN,NaN,True,0.022754
14308,231,États-Unis d'Amérique,2605,"Légumes, Autres",2013,vegetal,193.0,NaN,43.0,66.66,...,5.023200e+12,2.383100e+08,235.455163,1.117043,False,NaN,NaN,NaN,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,10,Australie,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,52.0,63.09,...,4.430501e+11,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True,NaN
5566,95,Honduras,2511,Blé,2013,vegetal,6.0,NaN,294.0,37.36,...,8.687818e+11,2.207415e+07,2876.760795,7.309321,True,NaN,NaN,NaN,True,NaN
4904,81,Ghana,2601,Tomates,2013,vegetal,NaN,NaN,16.0,26.07,...,1.512852e+11,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True,NaN
12055,194,Arabie saoudite,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,45.0,63.07,...,4.735163e+11,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True,NaN
9626,150,Pays-Bas,2556,Arachides Decortiquees,2013,vegetal,NaN,NaN,18.0,1.15,...,1.101066e+11,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True,NaN

In [76]:
#le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)
Top200["Ration_animal_et_ani_hum"]=Top200["Aliments pour animaux"]/Top200["Nourriture"]
Top200

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit,Ration_quanti_inter,Ration_animal_et_ani_hum
3674,59,Égypte,2511,Blé,2013,vegetal,4860.0,NaN,1175.0,146.83,...,1.066835e+09,2920.963396,8.854869,True,NaN,NaN,NaN,True,NaN,0.403386
1333,21,Brésil,2511,Blé,2013,vegetal,600.0,1.0,384.0,53.00,...,7.459477e+08,2644.325605,7.023990,True,NaN,NaN,NaN,True,0.000083,0.056497
15605,351,Chine,2511,Blé,2013,vegetal,26694.0,2948.0,546.0,63.10,...,8.997252e+09,3158.521093,10.065617,True,NaN,NaN,NaN,True,0.023221,0.298637
6128,101,Indonésie,2511,Blé,2013,vegetal,202.0,155.0,183.0,25.45,...,4.459733e+08,2624.182307,7.012159,True,NaN,NaN,NaN,True,0.022754,0.031761
14308,231,États-Unis d'Amérique,2605,"Légumes, Autres",2013,vegetal,193.0,NaN,43.0,66.66,...,2.383100e+08,235.455163,1.117043,False,NaN,NaN,NaN,True,NaN,0.009047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,10,Australie,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,52.0,63.09,...,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True,NaN,NaN
5566,95,Honduras,2511,Blé,2013,vegetal,6.0,NaN,294.0,37.36,...,2.207415e+07,2876.760795,7.309321,True,NaN,NaN,NaN,True,NaN,0.019868
4904,81,Ghana,2601,Tomates,2013,vegetal,NaN,NaN,16.0,26.07,...,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True,NaN,NaN
12055,194,Arabie saoudite,2605,"Légumes, Autres",2013,vegetal,NaN,NaN,45.0,63.07,...,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True,NaN,NaN
9626,150,Pays-Bas,2556,Arachides Decortiquees,2013,vegetal,NaN,NaN,18.0,1.15,...,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True,NaN,NaN

# Question 12

In [77]:
Top200_ratio_inter=Top200.sort_values(by='Ration_quanti_inter',ascending=False)
Top200_ratio_inter =Top200_ratio_inter[[ 'Produit','Code Produit','Zone','Code zone', 'Année', 'Origine',
       'Aliments pour animaux', 'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)', 'Pctage(poids_Port/poids_Total)',
       'is_cereal', 'Valeur_cereal', 'Unite_cereal', 'Pays_est_SousNutrition',
       'Top15_Produit', 'Ration_quanti_inter', 'Ration_animal_et_ani_hum']]
Top200_ratio_inter

,Produit,Code Produit,Zone,Code zone,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit,Ration_quanti_inter,Ration_animal_et_ani_hum
14798,Blé,2511,Éthiopie,238,2013,vegetal,NaN,1600.0,284.0,31.26,...,2.909179e+08,3315.604915,9.888441,True,NaN,NaN,NaN,True,0.326131,NaN
8965,Blé,2511,Mexique,138,2013,vegetal,67.0,1675.0,255.0,35.21,...,3.076466e+08,2643.001602,7.141287,True,NaN,NaN,NaN,True,0.263863,0.015552
10616,Blé,2511,Tchéquie (la),167,2013,vegetal,1350.0,692.0,703.0,92.67,...,7.933553e+07,2768.225494,7.997533,True,NaN,NaN,NaN,True,0.209570,1.360887
8426,Pommes de Terre,2531,Malaisie,131,2013,vegetal,10.0,83.0,19.0,10.97,...,4.013281e+06,632.169923,1.231068,False,NaN,NaN,NaN,True,0.190367,0.030675
10333,Blé,2511,Norvège,162,2013,vegetal,65.0,137.0,818.0,97.12,...,4.373491e+07,3072.833694,8.925492,True,NaN,NaN,NaN,True,0.186903,0.132653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,"Légumes, Autres",2605,Australie,10,2013,vegetal,NaN,NaN,52.0,63.09,...,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True,NaN,NaN
5566,Blé,2511,Honduras,95,2013,vegetal,6.0,NaN,294.0,37.36,...,2.207415e+07,2876.760795,7.309321,True,NaN,NaN,NaN,True,NaN,0.019868
4904,Tomates,2601,Ghana,81,2013,vegetal,NaN,NaN,16.0,26.07,...,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True,NaN,NaN
12055,"Légumes, Autres",2605,Arabie saoudite,194,2013,vegetal,NaN,NaN,45.0,63.07,...,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True,NaN,NaN
9626,Arachides Decortiquees,2556,Pays-Bas,150,2013,vegetal,NaN,NaN,18.0,1.15,...,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True,NaN,NaN

In [78]:
Top200_ratio_inter['Ration_quanti_inter'][:3]

14798    0.326131
8965     0.263863
10616    0.209570
Name: Ration_quanti_inter, dtype: float64

In [79]:
Top200_ration_ani_hum=Top200.sort_values(by='Ration_animal_et_ani_hum',ascending=False)
Top200_ration_ani_hum =Top200_ration_ani_hum[[ 'Produit','Code Produit','Zone','Code zone', 'Année', 'Origine',
       'Aliments pour animaux', 'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)', 'Pctage(poids_Port/poids_Total)',
       'is_cereal', 'Valeur_cereal', 'Unite_cereal', 'Pays_est_SousNutrition',
       'Top15_Produit', 'Ration_quanti_inter', 'Ration_animal_et_ani_hum']]
Top200_ration_ani_hum

,Produit,Code Produit,Zone,Code zone,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit,Ration_quanti_inter,Ration_animal_et_ani_hum
3231,Blé,2511,Danemark,54,2013,vegetal,3288.0,4.0,623.0,98.00,...,4.019833e+07,2318.933766,7.295522,True,NaN,NaN,NaN,True,0.000982,5.967332
9604,Blé,2511,Pays-Bas,150,2013,vegetal,2900.0,656.0,558.0,70.17,...,1.093726e+08,2902.470689,9.300390,True,NaN,NaN,NaN,True,0.133850,2.465986
13335,Blé,2511,Thaïlande,216,2013,vegetal,1130.0,NaN,76.0,10.93,...,5.332065e+07,2535.996098,7.274305,True,NaN,NaN,NaN,True,NaN,1.541610
10616,Blé,2511,Tchéquie (la),167,2013,vegetal,1350.0,692.0,703.0,92.67,...,7.933553e+07,2768.225494,7.997533,True,NaN,NaN,NaN,True,0.209570,1.360887
12562,Blé,2511,Espagne,203,2013,vegetal,5800.0,70.0,685.0,93.88,...,3.788792e+08,2663.546691,8.601117,True,NaN,NaN,NaN,True,0.006465,1.316686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12019,Pommes de Terre,2531,Arabie saoudite,194,2013,vegetal,NaN,NaN,39.0,23.24,...,6.524003e+06,612.508679,0.973732,False,NaN,NaN,NaN,True,NaN,NaN
644,"Légumes, Autres",2605,Australie,10,2013,vegetal,NaN,NaN,52.0,63.09,...,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True,NaN,NaN
4904,Tomates,2601,Ghana,81,2013,vegetal,NaN,NaN,16.0,26.07,...,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True,NaN,NaN
12055,"Légumes, Autres",2605,Arabie saoudite,194,2013,vegetal,NaN,NaN,45.0,63.07,...,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True,NaN,NaN
9626,Arachides Decortiquees,2556,Pays-Bas,150,2013,vegetal,NaN,NaN,18.0,1.15,...,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True,NaN,NaN

In [80]:
Top33=Top200_ration_ani_hum.sort_values(by='Ration_animal_et_ani_hum',ascending=False)
Top33

,Produit,Code Produit,Zone,Code zone,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit,Ration_quanti_inter,Ration_animal_et_ani_hum
3231,Blé,2511,Danemark,54,2013,vegetal,3288.0,4.0,623.0,98.00,...,4.019833e+07,2318.933766,7.295522,True,NaN,NaN,NaN,True,0.000982,5.967332
9604,Blé,2511,Pays-Bas,150,2013,vegetal,2900.0,656.0,558.0,70.17,...,1.093726e+08,2902.470689,9.300390,True,NaN,NaN,NaN,True,0.133850,2.465986
13335,Blé,2511,Thaïlande,216,2013,vegetal,1130.0,NaN,76.0,10.93,...,5.332065e+07,2535.996098,7.274305,True,NaN,NaN,NaN,True,NaN,1.541610
10616,Blé,2511,Tchéquie (la),167,2013,vegetal,1350.0,692.0,703.0,92.67,...,7.933553e+07,2768.225494,7.997533,True,NaN,NaN,NaN,True,0.209570,1.360887
12562,Blé,2511,Espagne,203,2013,vegetal,5800.0,70.0,685.0,93.88,...,3.788792e+08,2663.546691,8.601117,True,NaN,NaN,NaN,True,0.006465,1.316686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12019,Pommes de Terre,2531,Arabie saoudite,194,2013,vegetal,NaN,NaN,39.0,23.24,...,6.524003e+06,612.508679,0.973732,False,NaN,NaN,NaN,True,NaN,NaN
644,"Légumes, Autres",2605,Australie,10,2013,vegetal,NaN,NaN,52.0,63.09,...,1.908524e+07,300.780815,1.295671,False,2035.0,Milliers de tonnes,True,True,NaN,NaN
4904,Tomates,2601,Ghana,81,2013,vegetal,NaN,NaN,16.0,26.07,...,7.280600e+06,224.126222,1.078607,False,NaN,NaN,NaN,True,NaN,NaN
12055,"Légumes, Autres",2605,Arabie saoudite,194,2013,vegetal,NaN,NaN,45.0,63.07,...,2.030859e+07,260.460025,1.117084,False,NaN,NaN,NaN,True,NaN,NaN
9626,Arachides Decortiquees,2556,Pays-Bas,150,2013,vegetal,NaN,NaN,18.0,1.15,...,5.015969e+06,5795.085789,26.399835,False,NaN,NaN,NaN,True,NaN,NaN

In [81]:
Top200_ration_ani_hum['Ration_animal_et_ani_hum'][:3]

3231     5.967332
9604     2.465986
13335    1.541610
Name: Ration_animal_et_ani_hum, dtype: float64

# Question 13

In [82]:
F_ceréales['Zone'].unique()

array(['Arménie', 'Afghanistan', 'Albanie', 'Algérie', 'Angola',
       'Antigua-et-Barbuda', 'Argentine', 'Australie', 'Autriche',
       'Bahamas', 'Barbade', 'Bangladesh', 'Bermudes',
       'Bolivie (État plurinational de)', 'Botswana', 'Brésil', 'Belize',
       'Îles Salomon', 'Brunéi Darussalam', 'Bulgarie', 'Myanmar',
       'Cameroun', 'Canada', 'Cabo Verde', 'République centrafricaine',
       'Sri Lanka', 'Tchad', 'Chili', 'Colombie', 'Congo', 'Costa Rica',
       'Cuba', 'Chypre', 'Azerbaïdjan', 'Bénin', 'Danemark', 'Dominique',
       'République dominicaine', 'Bélarus', 'Équateur', 'Égypte',
       'El Salvador', 'Estonie', 'Fidji', 'Finlande', 'France',
       'Polynésie française', 'Djibouti', 'Géorgie', 'Gabon', 'Gambie',
       'Allemagne', 'Bosnie-Herzégovine', 'Ghana', 'Kiribati', 'Grèce',
       'Grenade', 'Guatemala', 'Guinée', 'Guyana', 'Haïti', 'Honduras',
       'Hongrie', 'Croatie', 'Islande', 'Inde', 'Indonésie',
       "Iran (République islamique d')", 'Iraq', 'Irlande', 'Israël',
       'Italie', "Côte d'Ivoire", 'Kazakhstan', 'Jamaïque', 'Japon',
       'Jordanie', 'Kirghizistan', 'Kenya', 'Cambodge',
       'République populaire démocratique de Corée',
       'République de Corée', 'Koweït', 'Lettonie',
       'République démocratique populaire lao', 'Liban', 'Lesotho',
       'Libéria', 'Lituanie', 'Madagascar', 'Malawi', 'Malaisie',
       'Maldives', 'Mali', 'Malte', 'Mauritanie', 'Maurice', 'Mexique',
       'Mongolie', 'Maroc', 'Mozambique', 'République de Moldova',
       'Namibie', 'Népal', 'Pays-Bas', 'Nouvelle-Calédonie',
       'Macédoine du Nord', 'Vanuatu', 'Nouvelle-Zélande', 'Nicaragua',
       'Niger', 'Nigéria', 'Norvège', 'Pakistan', 'Panama',
       'Tchéquie (la)', 'Paraguay', 'Pérou', 'Philippines', 'Pologne',
       'Portugal', 'Guinée-Bissau', 'Timor-Leste', 'Zimbabwe', 'Roumanie',
       'Rwanda', 'Fédération de Russie', 'Saint-Kitts-et-Nevis',
       'Sainte-Lucie', 'Saint-Vincent-et-les Grenadines',
       'Sao Tomé-et-Principe', 'Arabie saoudite', 'Sénégal',
       'Sierra Leone', 'Slovénie', 'Slovaquie', 'Afrique du Sud',
       'Espagne', 'Suriname', 'Tadjikistan', 'Eswatini', 'Suède',
       'Suisse', 'Turkménistan', 'République-Unie de Tanzanie',
       'Thaïlande', 'Togo', 'Trinité-et-Tobago', 'Oman', 'Tunisie',
       'Turquie', 'Émirats arabes unis', 'Ouganda', 'Royaume-Uni',
       'Ukraine', "États-Unis d'Amérique", 'Burkina Faso', 'Uruguay',
       'Ouzbékistan', 'Venezuela (République bolivarienne du)',
       'Viet Nam', 'Éthiopie', 'Samoa', 'Yémen', 'Zambie', 'Belgique',
       'Luxembourg', 'Serbie', 'Monténégro', 'Soudan', 'Chine'],
      dtype=object)

In [83]:
Cereale_USA=F_ceréales[(F_ceréales['Zone'] == "États-Unis d'Amérique" )]

Cereale_USA

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Valeur,Symbole,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal
14263,231,États-Unis d'Amérique,2511,Blé,2013,vegetal,6196.0,16.0,599.0,80.43,...,320051,NaN,Donnée officielle,6.997435e+13,2.260440e+09,2718.295019,8.781137,True,NaN,NaN
14264,231,États-Unis d'Amérique,2513,Orge,2013,vegetal,1440.0,NaN,5.0,0.50,...,320051,NaN,Donnée officielle,5.840931e+11,1.635461e+07,3650.581719,10.221629,True,NaN,NaN
14265,231,États-Unis d'Amérique,2514,Maïs,2013,vegetal,128024.0,137023.0,92.0,12.24,...,320051,NaN,Donnée officielle,1.074731e+13,1.950871e+08,2743.761190,4.980523,True,NaN,NaN
14266,231,États-Unis d'Amérique,2515,Seigle,2013,vegetal,184.0,NaN,2.0,0.27,...,320051,NaN,Donnée officielle,2.336372e+11,8.177303e+06,2685.485402,9.399199,True,NaN,NaN
14267,231,États-Unis d'Amérique,2516,Avoine,2013,vegetal,1430.0,NaN,19.0,3.95,...,320051,NaN,Donnée officielle,2.219554e+12,9.228671e+07,1754.587893,7.295392,True,NaN,NaN
14269,231,États-Unis d'Amérique,2518,Sorgho,2013,vegetal,2351.0,NaN,7.0,0.74,...,320051,NaN,Donnée officielle,8.177303e+11,2.336372e+07,3464.958919,9.899883,True,NaN,NaN
14270,231,États-Unis d'Amérique,2520,"Céréales, Autres",2013,vegetal,77.0,NaN,5.0,0.62,...,320051,NaN,Donnée officielle,5.840931e+11,1.752279e+07,2920.465375,8.761396,True,NaN,NaN
14355,231,États-Unis d'Amérique,2805,Riz (Eq Blanchi),2013,vegetal,NaN,142.0,72.0,6.88,...,320051,NaN,Donnée officielle,8.410940e+12,1.553688e+08,3817.948379,7.052599,True,NaN,NaN

In [84]:
Tonne_cere=(Cereale_USA["Aliments pour animaux"]*1e6).sum()*0.10
Tonne_cere

13970200000.0

# Question  14

In [85]:
Cereale_Thai=Bilan[(Bilan['Zone'] == 'Thaïlande') & (Bilan['Produit']== 'Manioc' )]

Cereale_Thai['Exportations - Quantité']*1e6
Cereale_Thai

,Code zone,Zone,Code Produit,Produit,Année,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Description du Symbole,Disponibilité alimentaire (Kcal),Disponibilité de protéines en quantité (Kg),ratio_Energie_poid(kcal/kg),Pctage(poids_Port/poids_Total),is_cereal,Valeur_cereal,Unite_cereal,Pays_est_SousNutrition,Top15_Produit
13344,216,Thaïlande,2532,Manioc,2013,vegetal,1800.0,2081.0,40.0,13.0,...,Donnée officielle,9.783606e+11,3424262.1,1123.261309,0.393141,False,NaN,NaN,NaN,False

In [86]:
Total_exp=Bilan[Bilan["Produit"]=="Manioc"]["Exportations - Quantité"].sum()
                
Total_exp*1e6

35959000000.0

In [87]:
((Cereale_Thai['Exportations - Quantité']*1e6)/(Total_exp*1e6))*100

13344    70.118746
Name: Exportations - Quantité, dtype: float64

In [88]:
#Population Thaïlandese sous alimentation 
Sous_ali_Thai=Sous_alimentation_finale[Sous_alimentation_finale['Zone']=='Thaïlande']
Sous_ali_Thai

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
931,FS,Données de la sécurité alimentaire,216,Thaïlande,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,5.5,F,Estimation FAO,NaN

In [89]:
#Population generale de la Thaïlande 
Population_Thai=Population_finale[(Population_finale['Zone'] == 'Thaïlande')]
Population_Thai

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
160,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,216,Thaïlande,511,Population totale,2501,Population,2013,2013,1000 personnes,67011,NaN,Donnée officielle

In [90]:
#pourcentage de la population Thaïlandese sous nutrition 
round(((5.5*1e6)/(67011*1000))*100,2)

8.21

# Question 15

In [91]:
population.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='object')

In [92]:
# Utilisation de la librairie sqlite3
import sqlite3

# cette ligne va  créer la base de données " base_fao.db" 
conn = sqlite3.connect('base_fao.db')

In [93]:
c = conn.cursor()

In [94]:
Population=population

In [95]:
# Préparation de la table population à partir du dataframe (population)
df_pop = Population
df_pop = df_pop[['Code zone', 'Zone', 'Année', 'Valeur']].sort_values(by='Code zone')
df_pop = df_pop.rename(columns={'Code zone': 'code_pays', 'Zone': 'pays', 'Année': 'annee', 'Valeur': 'population'})
df_pop.population = df_pop.population * 1000

In [96]:
# DROP IF EXISTS
c.execute('DROP TABLE IF EXISTS Population')

# Création de la table population
c.execute('''CREATE TABLE Population(
           code_pays INTEGER,
           pays TEXT,
           annee INTEGER,
           population REAL,
           CONSTRAINT pays_annee PRIMARY KEY (code_pays, annee))''')

In [97]:
conn.commit()
df_pop.to_sql('Population', conn, if_exists='append', index=False)

In [98]:
#colonnes de BilanAlimentaire
Bilan.columns

Index(['Code zone', 'Zone', 'Code Produit', 'Produit', 'Année', 'Origine',
       'Aliments pour animaux', 'Autres utilisations (non alimentaire)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure', 'Exportations - Quantité',
       'Importations - Quantité', 'Nourriture', 'Pertes', 'Production',
       'Semences', 'Traitement', 'Variation de stock', 'Code Domaine',
       'Domaine', 'Code zone_y', 'Code Élément', 'Élément', 'Code Produit_y',
       'Produit_y', 'Code année', 'Année_y', 'Unité', 'Valeur', 'Symbole',
       'Description du Symbole', 'Disponibilité alimentaire (Kcal)',
       'Disponibilité de protéines en quantité (Kg)',
       'ratio_Energie_poid(kcal/kg)', 'Pctage(poids_Port/poids_Total)',
       'is_cereal', 'Valeur_cereal', 'Unite_cereal', 'Pays_est_SousNutrition',
       'Top15_Produit'],
      dtype='object')

In [99]:
dispo_alim =BilanAlimentaire_pivot

In [100]:
# Préparation de la table dispo_alim à partir du dataframe (Bilan)
df_pop = BilanAlimentaire_pivot
df_pop = df_pop[['Zone','Code zone','Année','Produit','Code Produit', 'Origine',
       'Disponibilité alimentaire (Kcal/personne/jour)','Disponibilité de matière grasse en quantité (g/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Disponibilité intérieure']].sort_values(by='Code zone')
df_pop = df_pop.rename(columns={'Zone': 'pays', 'Code zone':'code_pays','Année': 'année', 'Produit': 'produit','Code Produit':'code_produit','Origine':'origin','Disponibilité intérieure':'dispo_alim_tonnes','Disponibilité alimentaire (Kcal/personne/jour)':'dispo_alim_kcal_p_j','Disponibilité de protéines en quantité (g/personne/jour)':'dispo_prot','Disponibilité de matière grasse en quantité (g/personne/jour)':'dispo_mat_gr'})
df_pop.dispo_alim_tonnes = df_pop.dispo_alim_tonnes * 1e6

In [101]:
# DROP IF EXISTS
c.execute('DROP TABLE IF EXISTS dispo_alim')

# Création de la table dispo_alim
c.execute('''CREATE TABLE dispo_alim(
            pays TEXT,
            code_pays INTEGER,
            année INTEGER,
            produit TEXT,
            code_produit INTEGER, 
            origin TEXT, 
            dispo_alim_tonnes REAL,
            dispo_alim_kcal_p_j REAL,
            dispo_prot REAL ,
            dispo_mat_gr REAL,
            CONSTRAINT pays_produit PRIMARY KEY (code_pays, code_produit))''')

In [102]:
df_pop.to_sql('dispo_alim', conn, if_exists='append', index=False)
conn.commit()

# QUESTION 16

In [103]:
equilibre_prod = Bilan

In [104]:
# Préparation de la table equilibre_prod à partir du dataframe (population)
df_pop = equilibre_prod
df_pop = df_pop[[ 'Zone','Code zone', 'Code Produit', 'Produit','Année','Aliments pour animaux', 'Autres utilisations (non alimentaire)', 'Nourriture', 'Pertes','Disponibilité intérieure',
       'Semences', 'Traitement']].sort_values(by='Code zone')
df_pop = df_pop.rename(columns={'Zone':'pays','Code zone':'code_pays','Année':'année','Produit':'produit','Code Produit':'code_produit','Disponibilité intérieure':'dispo_int','Aliments pour animaux':'alim_ani','Semences':'semences','Pertes':'pertes','Traitement':'transfo','Nourriture':'nourriture','Autres utilisations (non alimentaire)':'autres_utilisations'})
df_pop.dispo_int = df_pop.dispo_int *1000
df_pop.alim_ani = df_pop.alim_ani*1000
df_pop.pertes = df_pop.pertes*1000
df_pop.semences = df_pop.semences*1000
df_pop.transfo = df_pop.transfo*1000
df_pop.nourriture = df_pop.nourriture*1000
df_pop.autres_utilisations = df_pop.autres_utilisations*1000

In [105]:
# DROP IF EXISTS
c.execute('DROP TABLE IF EXISTS equilibre_prod')

# Création de la table dispo_alim
c.execute('''CREATE TABLE equilibre_prod(
            pays TEXT,
            code_pays INTEGER,
            année INTEGER,
            produit TEXT,
            code_produit INTEGER,
            dispo_int REAL,
            alim_ani REAL ,
            semences REAL ,
            pertes REAL,
            transfo REAL ,
            nourriture REAL,
            autres_utilisations REAL,
            CONSTRAINT pays_produit PRIMARY KEY (code_pays, code_produit))''')

In [106]:
df_pop.to_sql('equilibre_prod', conn, if_exists='append', index=False)
conn.commit()

# QUESTION 17

In [107]:
Sous_alimentation_finale.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole', 'Note'],
      dtype='object')

In [108]:
sous_nutrition=Sous_alimentation_finale

In [109]:
# Préparation de la table population à partir du dataframe (population)
df_pop = sous_nutrition
df_pop = df_pop[['Zone','Code zone', 'Année', 'Valeur']].sort_values(by='Code zone')
df_pop = df_pop.rename(columns={'Zone': 'pays','Code zone': 'code_pays','Année': 'année', 'Valeur': 'nb_personnes'}) 
df_pop.nb_personnes = df_pop.nb_personnes*1e6

In [110]:
# DROP IF EXISTS
c.execute('DROP TABLE IF EXISTS sous_nutrition')

# Création de la table sous_nutrition
c.execute('''CREATE TABLE sous_nutrition(
          pays TEXT,
          code_pays INTEGER,
          année INTEGER, 
          nb_personnes REAL,
           CONSTRAINT pays_annee PRIMARY KEY (code_pays, année))''')

In [111]:
conn.commit()
df_pop.to_sql('sous_nutrition', conn, if_exists='append', index=False)

# Question 19

In [112]:
#1-A Les 10 pays ayant le plus haut ratio disponibilité alimentaire/habitant en termes de protéines (en Kg) par habitant
pd.read_sql_query("""
SELECT pays, SUM(dispo_prot/1e3*365) AS ratio_dispo_prot_kg
FROM dispo_alim
WHERE année = 2013
GROUP BY pays
ORDER BY(ratio_dispo_prot_kg)
DESC LIMIT 10;
""",conn)

                       pays  ratio_dispo_prot_kg
0                   Islande             48.56690
1  Chine - RAS de Hong-Kong             47.11055
2                    Israël             46.72000
3                  Lituanie             45.39140
4                  Maldives             44.64680
5                  Finlande             42.90940
6                Luxembourg             41.47860
7                Monténégro             40.84350
8                  Pays-Bas             40.68290
9                   Albanie             40.65005

In [113]:
#1-B  Les 10 pays ayant le plus haut ratio disponibilité alimentaire/habitant en termes de protéines (en kcal) par habitant
pd.read_sql_query("""
SELECT pays, SUM(dispo_alim_kcal_p_j) AS ratio_dispo_kcal
FROM dispo_alim
WHERE année = 2013
GROUP BY pays
ORDER BY(ratio_dispo_kcal)
DESC LIMIT 10 ;
""",conn)

                    pays  ratio_dispo_kcal
0               Autriche            3770.0
1               Belgique            3737.0
2                Turquie            3708.0
3  États-Unis d'Amérique            3682.0
4                 Israël            3610.0
5                Irlande            3602.0
6                 Italie            3578.0
7             Luxembourg            3540.0
8                 Égypte            3518.0
9              Allemagne            3503.0

In [114]:
#2 Les 10 pays ayant le plus faible ratio disponibilité alimentaire/habitant en termes de protéines (en Kg) par habitant
pd.read_sql_query("""
SELECT pays, SUM(dispo_prot/1e3*365) AS ratio_dispo_prot_kg_hab
FROM dispo_alim
WHERE année = 2013
GROUP BY pays
ORDER BY(ratio_dispo_prot_kg_hab)
ASC LIMIT 10;
""",conn)

                        pays  ratio_dispo_prot_kg_hab
0                    Libéria                 13.74590
1              Guinée-Bissau                 16.07825
2                 Mozambique                 16.67320
3  République centrafricaine                 16.80460
4                 Madagascar                 17.04185
5                      Haïti                 17.41050
6                   Zimbabwe                 17.63680
7                      Congo                 18.76465
8                    Ouganda                 19.21360
9       Sao Tomé-et-Principe                 19.38150

In [115]:
#3 La quantité totale (en kg) de produits perdus par pays en 2013
pd.read_sql_query("""
SELECT pays,SUM(pertes) as perte
FROM equilibre_prod 
GROUP BY pays
ORDER BY perte DESC LIMIT 10;

""",conn)

        pays       perte
0      Chine  88892000.0
1     Brésil  75817000.0
2       Inde  54918000.0
3    Nigéria  18960000.0
4  Indonésie  13030000.0
5    Turquie  10703000.0
6     Égypte   7603000.0
7      Ghana   7442000.0
8    Mexique   6756000.0
9   Viet Nam   6740000.0

In [116]:
#4 Les 10 pays pour lesquels la proportion de personnes sous-alimentées est la plus forte
pd.read_sql_query("""
SELECT sous_nutrition.pays,sous_nutrition.nb_personnes/Population.population as proportion_pays_pop
FROM sous_nutrition,Population
WHERE sous_nutrition.pays=Population.pays
ORDER BY proportion_pays_pop DESC LIMIT 10;
""",conn)

                                         pays  proportion_pays_pop
0                   République centrafricaine             0.519931
1                                    Zimbabwe             0.508834
2                                       Haïti             0.504022
3                                      Zambie             0.481464
4  République populaire démocratique de Corée             0.437839
5                                       Congo             0.427158
6                                  Madagascar             0.396947
7                                     Libéria             0.395901
8                                       Tchad             0.389864
9                                     Ouganda             0.361904

In [117]:
#5 Les 10 produits pour lesquels le ratio Autres utilisations/Disponibilité intérieure est le plus élevé.
pd.read_sql_query("""
SELECT  produit,SUM (autres_utilisations)/SUM (dispo_int) as ratio
FROM equilibre_prod
GROUP BY produit
ORDER BY ratio DESC LIMIT 10 ; 

""",conn)

                   produit     ratio
0           Huile de Palme  0.670373
1  Huil Plantes Oleif Autr  0.528792
2   Graisses Animales Crue  0.478207
3   Huile de Germe de Maïs  0.455556
4  Huile de Colza&Moutarde  0.445787
5            Huile de Coco  0.379808
6         Huile d'Arachide  0.333333
7     Sucre non centrifugé  0.290407
8            Huile de Soja  0.268594
9             Sucre, canne  0.266228

# Question 20

#HUILE DE PALME

#Biocarburant: Huile de Palme est utiliser pour la fabrication de Biocarburant l'huile de palme est de plus en plus utilisée pour produire des carburants. Toujours selon Transport & Environnement, cette part est passée en dix ans d'environ 15 % à 53 % du total. Elle avait dépassé les 50 %, pour la première fois, en 2017. En France, en 2018, on atteint même 70 % des importations pour cet usage. C'est notamment le groupe Total qui est concerné. Le pétrolier prévoit de s'approvisionner en huile de palme « durable et certifiée » à hauteur de 300 000 tonnes par an au maximum, pour sa raffinerie de La Mède (Bouches-du-Rhône). De ce site, exploité depuis début juillet, sont censés sortir des carburants « propres ».

cosmétiques :
l’huile de palme est souvent utilisée comme matière première dans les processus de saponification (fabrication du savon), mais permet également de constituer d’autres composants, par exemple des émulsifiants, indispensables pour la formulation des cosmétiques. On retrouve également de nombreux composants annexes (des agents texturants, des huiles hydrogérénées,etc) issus d’huile de palme.

En tant que matière première pure, l’huile de palme est une huile végétale qui peut représenter certains avantages : comme la plupart des huiles végétales, elle est émolliente, nourrissante et protectrice. En ce qui concerne la fabrication des savons, l’huile de palme assure la consistance nécessaire qui permet d’éviter que les savons ne ramollissent ou se liquéfient trop rapidement.

#HUILE DE COCO
| 
#Les atouts de l’huile de coco

Qui est utilisée depuis des siècles pour nourrir cheveux et épidermes dans des contrées exotiques où pousse la précieuse noix. 

Les secrets de composition de l’huile de coco
Si l’huile de coco est un ingrédient phare en cosmétique, c’est grâce à ses propriétés nourrissantes et réparatrices. Très riche en acides gras essentiels, en acide laurique et en acide myristique, elle possède une action relipidante et est très facilement absorbée par la peau.

Les atouts de l’huile de coco pour la peau

Très nourrissante, l’huile de coco aide à lutter contre la déshydratation. "C’est une huile assez douce aux vertus réparatrices"

Les atouts de l’huile de coco pour les cheveux

L’acide laurique que contient l’huile de coco possède une forte affinité avec les protéines des cheveux. Résultat, elle les nourrit en profondeur. C’est un vrai bonheur pour les cheveux secs et les cheveux crépus.

l’huile de coco dans de très nombreux cosmétiques : huiles capillaires, savons, baumes et laits corporels, crèmes mains, gammes de shampoings, soins visage…

purifier l'eau et blanchir les dents